export * from './app.service';
import { AppService } from './app.service';
export * from './app.serviceInterface';
export * from './appointment.service';
import { AppointmentService } from './appointment.service';
export * from './appointment.serviceInterface';
export * from './cognitiveScores.service';
import { CognitiveScoresService } from './cognitiveScores.service';
export * from './cognitiveScores.serviceInterface';
export * from './patient.service';
import { PatientService } from './patient.service';
export * from './patient.serviceInterface';
export * from './predictions.service';
import { PredictionsService } from './predictions.service';
export * from './predictions.serviceInterface';
export const APIS = [AppService, AppointmentService, CognitiveScoresService, PatientService, PredictionsService];
