/**
 * Cognitive Care Backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { AppointmentDto } from '../model/models';
import { CreateAppointmentDto } from '../model/models';
import { TranscriptionDto } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface CreateOrUpdateAppointmentRequestParams {
    createAppointmentDto: CreateAppointmentDto;
}

export interface FindAppoinmentByIdRequestParams {
    id: string;
}

export interface GetAudioForAppointmentRequestParams {
    id: string;
}

export interface TranscribeAppointmentAudioRequestParams {
    id: string;
}

export interface UploadAudioFileRequestParams {
    id: string;
    file?: Blob;
}


export interface AppointmentServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    createOrUpdateAppointment(requestParameters: CreateOrUpdateAppointmentRequestParams, extraHttpRequestParams?: any): Observable<AppointmentDto>;

    /**
     * 
     * 
* @param requestParameters
     */
    findAppoinmentById(requestParameters: FindAppoinmentByIdRequestParams, extraHttpRequestParams?: any): Observable<AppointmentDto>;

    /**
     * 
     * 
* @param requestParameters
     */
    getAudioForAppointment(requestParameters: GetAudioForAppointmentRequestParams, extraHttpRequestParams?: any): Observable<Blob>;

    /**
     * 
     * 
* @param requestParameters
     */
    transcribeAppointmentAudio(requestParameters: TranscribeAppointmentAudioRequestParams, extraHttpRequestParams?: any): Observable<TranscriptionDto>;

    /**
     * 
     * 
* @param requestParameters
     */
    uploadAudioFile(requestParameters: UploadAudioFileRequestParams, extraHttpRequestParams?: any): Observable<{}>;

}
