/**
 * Cognitive Care Backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CognitiveScoreDto } from '../model/models';
import { CreateCognitiveScoreDto } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface CreateOrUpdateCognitiveScoreRequestParams {
    createCognitiveScoreDto: CreateCognitiveScoreDto;
}

export interface FindScoreByIdRequestParams {
    id: string;
}


export interface CognitiveScoresServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    createOrUpdateCognitiveScore(requestParameters: CreateOrUpdateCognitiveScoreRequestParams, extraHttpRequestParams?: any): Observable<CognitiveScoreDto>;

    /**
     * 
     * 
* @param requestParameters
     */
    findScoreById(requestParameters: FindScoreByIdRequestParams, extraHttpRequestParams?: any): Observable<CognitiveScoreDto>;

}
