/**
 * Cognitive Care Backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { HttpHeaders }                                       from '@angular/common/http';

import { Observable }                                        from 'rxjs';

import { CreatePatientDto } from '../model/models';
import { PatientDto } from '../model/models';
import { PatientSmallDto } from '../model/models';


import { Configuration }                                     from '../configuration';


export interface CreatePatientRequestParams {
    createPatientDto: CreatePatientDto;
}

export interface FindPatientByIdRequestParams {
    id: string;
}

export interface RemovePatientByIdRequestParams {
    id: string;
}

export interface SearchPatientsRequestParams {
    query?: string;
}


export interface PatientServiceInterface {
    defaultHeaders: HttpHeaders;
    configuration: Configuration;

    /**
     * 
     * 
* @param requestParameters
     */
    createPatient(requestParameters: CreatePatientRequestParams, extraHttpRequestParams?: any): Observable<PatientDto>;

    /**
     * 
     * 
* @param requestParameters
     */
    findPatientById(requestParameters: FindPatientByIdRequestParams, extraHttpRequestParams?: any): Observable<PatientDto>;

    /**
     * 
     * 
* @param requestParameters
     */
    removePatientById(requestParameters: RemovePatientByIdRequestParams, extraHttpRequestParams?: any): Observable<PatientDto>;

    /**
     * 
     * 
* @param requestParameters
     */
    searchPatients(requestParameters: SearchPatientsRequestParams, extraHttpRequestParams?: any): Observable<Array<PatientSmallDto>>;

}
