/**
 * Cognitive Care Backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AppointmentSmallDto { 
    id: string;
    patientId: string;
    date: string;
}

