/**
 * Cognitive Care Backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface AppointmentDto { 
    date: string;
    id: string;
    createdAt: string;
    updatedAt: string;
    patientId: string;
    audioFile?: string;
    notes?: string;
    transcription?: string;
    transcriptionSummary?: string;
}

