/**
 * Cognitive Care Backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateCognitiveScoreDto { 
    id?: string;
    patientId: string;
    assessmentDate: string;
    toolUsed: string;
    scores: object;
}

