/**
 * Cognitive Care Backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateAppointmentDto { 
    transcriptionSummary?: string | null;
    id?: string;
    patientId: string;
    date: string;
}

