/**
 * Cognitive Care Backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PatientSmallDto { 
    patientName: string;
    patientId: string;
    patientDni: string;
    nextAppointment: string;
    lastAppointment: string;
}

