/**
 * Cognitive Care Backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PatientDto { 
    id: string;
    fullName: string;
    dni: string;
    birthDate: string;
    summary: string;
    aiSummary: string;
    symptoms: string;
    aiSymptoms: string;
    notes: string;
}

