/**
 * Cognitive Care Backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RelapseRisk } from './relapseRisk.model';
import { AnomalyDetection } from './anomalyDetection.model';
import { CognitiveDeclineRisk } from './cognitiveDeclineRisk.model';


export interface PredictionDataDto { 
    patient_id: number;
    cognitive_decline_risk: CognitiveDeclineRisk;
    relapse_risk: RelapseRisk;
    anomaly_detection: AnomalyDetection;
}

