/**
 * Cognitive Care Backend
 *
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PredictionDataDto } from './predictionDataDto.model';


export interface PredictionDto { 
    status: PredictionDto.StatusEnum;
    patientId: string;
    predictionData: PredictionDataDto;
}
export namespace PredictionDto {
    export type StatusEnum = 'completed' | 'processing' | 'error';
    export const StatusEnum = {
        Completed: 'completed' as StatusEnum,
        Processing: 'processing' as StatusEnum,
        Error: 'error' as StatusEnum
    };
}


