version: '3.8' 

services:
  postgres:
    image: postgres:17-alpine  
    environment:
      POSTGRES_USER: root      
      POSTGRES_PASSWORD: root  
      POSTGRES_DB: cognitivecare      
    ports:
      - "5432:5432"   
    volumes:
      - postgres-data:/var/lib/postgresql/data
volumes:
  postgres-data:
